### ISSUE TITLE
Upgrade fabric to 2.x

### ISSUE THREAD

**Issue by kabirbaidhya** [kabirbaidhya/boss#140]
- Upgrade fabric to 2.4.x (http://www.fabfile.org/upgrading.html)
- There are a lot of breaking changes, need to fix all those and do a regression test to ensure things still work.
- There might be few breaking changes in boss too, but should be minimized as much as possible.
- This enables python3 support too.

**Comment by mesaugat** [comment]
I think this would be good even though it might involve a lot of changes.

**Comment by kabirbaidhya** [comment]
@mesaugat Sure, thanks. You can work on it if you like. Heads up - there could be lots of changes but you can focus on only the changes are are required for the upgrade, rest can go in separate PRs.

I tried this long before, but checked out after realizing there were more to do :smile:.

You can start from here - http://www.fabfile.org/upgrading.html.

You may draft a PR and I can help where needed.
